from .generic import distance_matrix
from .agglomerative_clustering import agglomerative_clustering
from .affinity_propagation import affinity_propagation
from .spectral_clustering import spectral_clustering